### ISSUE TITLE
Make it a Leiningen project?

### ISSUE THREAD

**Issue by jonasseglare** [aiff22/Decision-Stream#2]
This project looks very interesting. However, I think it would be useful to turn it into a Leiningen project, so that we have the dependencies downloaded for us, etc, what do you think?

The main change would be to add this ```project.clj``` file to the root directory (see attached, renamed to ```.txt``` so that Github accepts the file.).

[project.txt](https://github.com/aiff22/Decision-Stream/files/1788809/project.txt)

**Comment by aiff22** [comment]
Hi @jonasseglare,

Sure, support for Leiningen is added.
